<?php

/*
|--------------------------------------------------------------------------
| Tour packages
|--------------------------------------------------------------------------
|
| One entry per package, keyed by slug. The homepage cards and the detail
| pages both read from here, so a price or duration is only ever edited once.
|
| Note: galleries currently reuse the four hero photographs. Swap in real
| per-tour imagery before launch.
|
*/

return [

    'great-migration-safari' => [
        'region' => 'northern',
        'tier' => 'classic',
        'name' => 'Great Migration Safari',
        'category' => 'Wildlife',
        'tagline' => 'Seven days tracking the herds across the Serengeti',
        'image' => '/assets/images/carousel/lionss_with_her_cub.jpg',
        'gallery' => [
            '/assets/images/carousel/lionss_with_her_cub.jpg',
            '/assets/images/carousel/Rhinos_in_Ngorongoro_Crater.jpg',
            '/assets/images/kili.jpg',
        ],
        'days' => '7 Days',
        'nights' => '6 Nights',
        'group' => 'Max 6',
        'difficulty' => 'Easy',
        'rating' => '4.9',
        'reviews' => '412',
        'price' => '$2,450',
        'price_note' => 'per person sharing, excluding international flights',
        'highlight' => 'Witnessing a cheetah hunt at sunrise',
        'location' => 'Northern Circuit, Tanzania',
        'best_time' => 'June – October',
        'start' => 'Arusha',
        'end' => 'Arusha',
        'summary' => [
            'Seven days following the largest land migration on earth. Over a million wildebeest and a quarter of a million zebra move in a slow clockwise loop through the Serengeti ecosystem, and this itinerary is built to intercept them rather than tour a fixed set of lodges.',
            'Your guide reroutes daily on radio reports from other vehicles in the network, so the plan below is the shape of the week, not a contract. Small groups of six keep every seat a window seat.',
        ],
        'highlights' => [
            'Track the herds with a guide who repositions daily on live sightings',
            'Three nights inside the Serengeti, not on its outskirts',
            'Ngorongoro Crater floor at first light, before the day visitors arrive',
            'Tarangire in elephant season, with baobabs and very few vehicles',
            'Optional hot-air balloon over the plains at dawn',
        ],
        'itinerary' => [
            [
                'day' => 1,
                'title' => 'Arusha — briefing and kit check',
                'copy' => 'Airport transfer, an afternoon briefing with your guide, and time to sort kit. Your guide walks through the week, the current position of the herds and how the plan may shift.',
                'stay' => 'Arusha lodge',
                'meals' => 'Dinner',
            ],
            [
                'day' => 2,
                'title' => 'Tarangire National Park',
                'copy' => 'A morning drive south to Tarangire, known for its elephant herds and ancient baobabs. Afternoon game drive along the river, where game concentrates as the dry season sets in.',
                'stay' => 'Tarangire camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 3,
                'title' => 'Into the Serengeti',
                'copy' => 'North through the Ngorongoro highlands and down onto the plains. Game driving begins the moment you cross the boundary — the drive in is often the day’s best sighting.',
                'stay' => 'Central Serengeti camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 4,
                'title' => 'Serengeti — full day with the herds',
                'copy' => 'A full day positioned wherever the migration is. Dawn and late afternoon are the working hours; the middle of the day is for lunch in the shade and watching a pride sleep it off.',
                'stay' => 'Central Serengeti camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 5,
                'title' => 'Serengeti — river crossings',
                'copy' => 'If the herds are near the Grumeti or Mara, the day is spent waiting at the crossings. Patience is the whole technique: the herd may build for hours before one animal commits.',
                'stay' => 'Central Serengeti camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 6,
                'title' => 'Ngorongoro Crater',
                'copy' => 'Descend 600 m to the crater floor for a half-day drive among the densest concentration of wildlife in Africa, including one of the last resident black rhino populations.',
                'stay' => 'Crater rim lodge',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 7,
                'title' => 'Return to Arusha',
                'copy' => 'A last highland drive back to Arusha, with a stop at a Maasai market if timing allows. Airport transfer for evening departures.',
                'stay' => '—',
                'meals' => 'Breakfast, lunch',
            ],
        ],
        'included' => [
            'All park and crater entry fees',
            'Private 4x4 safari vehicle with pop-up roof',
            'Professional English-speaking guide',
            'All accommodation as listed',
            'All meals from dinner on day 1',
            'Drinking water throughout',
            'Airport transfers',
        ],
        'excluded' => [
            'International flights and visa',
            'Travel insurance (required)',
            'Hot-air balloon safari (approx. $600)',
            'Alcoholic drinks',
            'Tips for guide and camp crew',
            'Personal items and laundry',
        ],
    ],

    'kilimanjaro-machame' => [
        'region' => 'kilimanjaro',
        'tier' => 'classic',
        'name' => 'Kilimanjaro · Machame Route',
        'category' => 'Mountain',
        'tagline' => 'Eight days on the Whiskey Route to Uhuru Peak',
        'image' => '/assets/images/kili.jpg',
        'gallery' => [
            '/assets/images/kili.jpg',
            '/assets/images/carousel/lionss_with_her_cub.jpg',
            '/assets/images/carousel/Rhinos_in_Ngorongoro_Crater.jpg',
        ],
        'days' => '8 Days',
        'nights' => '7 Nights',
        'group' => 'Max 10',
        'difficulty' => 'Challenging',
        'rating' => '4.8',
        'reviews' => '287',
        'price' => '$1,850',
        'price_note' => 'per person, all park fees and crew wages included',
        'highlight' => 'Standing at Uhuru Peak at dawn',
        'location' => 'Kilimanjaro Region, Tanzania',
        'best_time' => 'January – March, June – October',
        'start' => 'Moshi',
        'end' => 'Moshi',
        'summary' => [
            'Machame is the most walked route on Kilimanjaro for good reason: it climbs high and sleeps low, which is exactly what acclimatisation wants. Eight days rather than the minimum six gives your body the extra night it needs, and it is the single biggest factor in whether you summit.',
            'You walk through five climate zones — rainforest, heath, moorland, alpine desert and arctic summit — in under a week. Crews are paid above the KPAP guideline and carry loads within legal limits.',
        ],
        'highlights' => [
            'Eight-day profile with a proper acclimatisation day at Karanga',
            'Barranco Wall — a scramble, not a climb, and the best morning on the mountain',
            'Summit night timed to reach Uhuru Peak at sunrise',
            'Five climate zones between the gate and the crater rim',
            'Oxygen, pulse oximeter and a qualified mountain crew on every departure',
        ],
        'itinerary' => [
            [
                'day' => 1,
                'title' => 'Moshi — briefing and gear check',
                'copy' => 'Arrival, a full kit inspection with your lead guide, and a briefing on the route profile and altitude plan. Anything missing can be hired in town the same afternoon.',
                'stay' => 'Moshi hotel',
                'meals' => 'Dinner',
            ],
            [
                'day' => 2,
                'title' => 'Machame Gate to Machame Camp · 1,800 → 3,000 m',
                'copy' => 'Registration at the gate, then five to six hours climbing through dense rainforest. Expect mud, colobus monkeys and rain in the afternoon regardless of season.',
                'stay' => 'Machame Camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 3,
                'title' => 'Machame to Shira Camp · 3,000 → 3,840 m',
                'copy' => 'Out of the forest and onto the heath. A steep first hour, then the gradient eases across the Shira Plateau with the first clear view of Kibo.',
                'stay' => 'Shira Camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 4,
                'title' => 'Shira to Barranco via Lava Tower · 4,600 → 3,960 m',
                'copy' => 'The classic climb-high-sleep-low day. You touch 4,600 m at Lava Tower for lunch, then descend into the Barranco valley. Headaches here are normal and the point of the exercise.',
                'stay' => 'Barranco Camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 5,
                'title' => 'Barranco Wall to Karanga · 3,960 → 4,035 m',
                'copy' => 'The Wall looks impossible from camp and takes about ninety minutes of hands-on scrambling. A short day by design — the afternoon is rest.',
                'stay' => 'Karanga Camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 6,
                'title' => 'Karanga to Barafu · 4,035 → 4,673 m',
                'copy' => 'Three to four hours across alpine desert to base camp. An early dinner and bed by seven — you will be woken before midnight.',
                'stay' => 'Barafu Camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 7,
                'title' => 'Summit day — Uhuru Peak 5,895 m, descend to Mweka',
                'copy' => 'Leave around midnight for Stella Point at sunrise, then the final rim walk to Uhuru. Down to Barafu for a rest and food, then on to Mweka. Sixteen hours of walking, and the hardest and best day you will have.',
                'stay' => 'Mweka Camp',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 8,
                'title' => 'Mweka Gate to Moshi',
                'copy' => 'Three hours down through the forest to the gate, certificates issued, and a transfer back to Moshi for the longest shower of your life.',
                'stay' => '—',
                'meals' => 'Breakfast, lunch',
            ],
        ],
        'included' => [
            'All Kilimanjaro national park and rescue fees',
            'Mountain crew: lead guide, assistant guides, cook and porters',
            'Crew wages at or above KPAP guidelines',
            'All camping equipment and mess tent',
            'All meals on the mountain and drinking water',
            'Emergency oxygen and pulse oximeter',
            'Two nights hotel in Moshi and airport transfers',
        ],
        'excluded' => [
            'International flights and visa',
            'Travel insurance with cover to 6,000 m (required)',
            'Personal climbing gear and sleeping bag (hire available)',
            'Tips for the mountain crew',
            'Drinks and snacks beyond those provided',
        ],
    ],

    'ngorongoro-crater' => [
        'region' => 'northern',
        'tier' => 'mid-range',
        'name' => 'Ngorongoro Crater Descent',
        'category' => 'Wildlife',
        'tagline' => 'Four days in the caldera and the Rift Valley lakes',
        'image' => '/assets/images/carousel/Rhinos_in_Ngorongoro_Crater.jpg',
        'gallery' => [
            '/assets/images/carousel/Rhinos_in_Ngorongoro_Crater.jpg',
            '/assets/images/carousel/lionss_with_her_cub.jpg',
            '/assets/images/carousel/zanzibar_beach.jpg',
        ],
        'days' => '4 Days',
        'nights' => '3 Nights',
        'group' => 'Max 6',
        'difficulty' => 'Easy',
        'rating' => '4.9',
        'reviews' => '356',
        'price' => '$1,200',
        'price_note' => 'per person sharing, crater fees included',
        'highlight' => 'Black rhino on the crater floor',
        'location' => 'Arusha Region, Tanzania',
        'best_time' => 'Year round',
        'start' => 'Arusha',
        'end' => 'Arusha',
        'summary' => [
            'The Ngorongoro Crater is the largest intact volcanic caldera on earth — twenty kilometres across, six hundred metres deep, and home to around 25,000 large animals that mostly never leave. It is the densest wildlife concentration in Africa and one of the few places with a realistic chance of the Big Five in a single morning.',
            'Four days is enough to do it properly: an unhurried descent at first light, plus Lake Manyara on the way in. Short, and the best introduction to Tanzania if your time is limited.',
        ],
        'highlights' => [
            'Full descent to the crater floor, entering at dawn',
            'Realistic chance of black rhino, among the last free-ranging population',
            'Lake Manyara tree-climbing lions and flamingo flocks',
            'Maasai highlands and the crater rim at sunset',
            'Short enough to combine with Zanzibar the same trip',
        ],
        'itinerary' => [
            [
                'day' => 1,
                'title' => 'Arusha to Lake Manyara',
                'copy' => 'Drive west along the Rift Valley escarpment to Lake Manyara for an afternoon game drive. Groundwater forest, baboon troops, and flamingo on the soda flats when water levels allow.',
                'stay' => 'Karatu lodge',
                'meals' => 'Lunch, dinner',
            ],
            [
                'day' => 2,
                'title' => 'Ngorongoro Crater floor',
                'copy' => 'Early descent to be on the floor as the gates open. Six hours among lion, elephant, buffalo and — with luck and a good guide — black rhino on the Lerai side. Picnic lunch by the hippo pool.',
                'stay' => 'Crater rim lodge',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 3,
                'title' => 'Highlands and Maasai community visit',
                'copy' => 'A morning on the crater highlands with a Maasai community that manages grazing inside the conservation area. Afternoon at leisure on the rim, which is the best seat in the country.',
                'stay' => 'Crater rim lodge',
                'meals' => 'Breakfast, lunch, dinner',
            ],
            [
                'day' => 4,
                'title' => 'Return to Arusha',
                'copy' => 'A slow drive back through Karatu coffee country, arriving Arusha by early afternoon for onward flights.',
                'stay' => '—',
                'meals' => 'Breakfast, lunch',
            ],
        ],
        'included' => [
            'Ngorongoro conservation and crater descent fees',
            'Lake Manyara park fees',
            'Private 4x4 safari vehicle with pop-up roof',
            'Professional English-speaking guide',
            'All accommodation and meals as listed',
            'Maasai community visit fee',
            'Airport transfers',
        ],
        'excluded' => [
            'International flights and visa',
            'Travel insurance (required)',
            'Alcoholic drinks',
            'Tips for guide and lodge staff',
            'Personal items and laundry',
        ],
    ],

    'zanzibar-escape' => [
        'region' => 'zanzibar',
        'tier' => 'classic',
        'name' => 'Zanzibar Island Escape',
        'category' => 'Beach',
        'tagline' => 'Five days from Stone Town to the north coast',
        'image' => '/assets/images/carousel/zanzibar_beach.jpg',
        'gallery' => [
            '/assets/images/carousel/zanzibar_beach.jpg',
            '/assets/images/carousel/lionss_with_her_cub.jpg',
            '/assets/images/carousel/Rhinos_in_Ngorongoro_Crater.jpg',
        ],
        'days' => '5 Days',
        'nights' => '4 Nights',
        'group' => 'Max 12',
        'difficulty' => 'Easy',
        'rating' => '4.7',
        'reviews' => '198',
        'price' => '$890',
        'price_note' => 'per person sharing, island transfers included',
        'highlight' => 'Private dinner on a sandbank at sunset',
        'location' => 'Zanzibar Archipelago, Tanzania',
        'best_time' => 'June – October, December – February',
        'start' => 'Zanzibar Town',
        'end' => 'Zanzibar Town',
        'summary' => [
            'The standard way to finish a Tanzanian trip, and the reason so many safaris are booked with a beach week attached. Five days split between Stone Town — a UNESCO site of Omani doorways, spice markets and Swahili coral-rag alleys — and the white sand of the north coast.',
            'Deliberately unhurried. Two organised excursions, and the rest of the time is yours.',
        ],
        'highlights' => [
            'Guided Stone Town walk including the former slave market memorial',
            'Spice farm tour with a tasting lunch',
            'Snorkelling at Mnemba Atoll, the best reef on the island',
            'Sunset dhow cruise from Kendwa',
            'Private sandbank dinner, tide permitting',
        ],
        'itinerary' => [
            [
                'day' => 1,
                'title' => 'Arrival and Stone Town',
                'copy' => 'Airport transfer and an afternoon walking tour through the old town — the Old Fort, the House of Wonders, the carved doors and the fish market. Sunset from a rooftop.',
                'stay' => 'Stone Town hotel',
                'meals' => 'Dinner',
            ],
            [
                'day' => 2,
                'title' => 'Spice farm and north to Kendwa',
                'copy' => 'A morning at a working spice farm — clove, nutmeg, cardamom and vanilla — with lunch cooked on site. Transfer north to the coast in the afternoon.',
                'stay' => 'Kendwa beach resort',
                'meals' => 'Breakfast, lunch',
            ],
            [
                'day' => 3,
                'title' => 'Mnemba Atoll snorkelling',
                'copy' => 'Boat out to the Mnemba reef for two snorkel sessions in the island’s clearest water. Dolphins are common on the crossing. Afternoon free.',
                'stay' => 'Kendwa beach resort',
                'meals' => 'Breakfast, lunch',
            ],
            [
                'day' => 4,
                'title' => 'Free day and sunset dhow',
                'copy' => 'Nothing scheduled until late afternoon, when a traditional dhow takes you out for sunset. Sandbank dinner if the tide is right.',
                'stay' => 'Kendwa beach resort',
                'meals' => 'Breakfast, dinner',
            ],
            [
                'day' => 5,
                'title' => 'Departure',
                'copy' => 'A slow morning, then the transfer south to the airport. Day rooms available for late flights.',
                'stay' => '—',
                'meals' => 'Breakfast',
            ],
        ],
        'included' => [
            'All island transfers and airport pickups',
            'Four nights accommodation as listed',
            'Daily breakfast and meals as noted',
            'Guided Stone Town walking tour',
            'Spice farm tour with lunch',
            'Mnemba Atoll snorkelling trip and equipment',
            'Sunset dhow cruise',
        ],
        'excluded' => [
            'International flights and visa',
            'Travel insurance (required)',
            'Lunches and dinners not listed',
            'Alcoholic drinks',
            'Diving, kitesurfing and other optional activities',
            'Tips',
        ],
    ],

];
